import os
import shutil
import re
import argparse


def generate_unique_dir(base_dir, prefix, sub_suffix):
    """
    Generates a new unique directory name like:
    prefix_single_phase_1, prefix_single_phase_2, etc.
    """
    counter = 1
    while True:
        dirname = f"{prefix}_{sub_suffix}_{counter}"
        full_path = os.path.join(base_dir, dirname)
        if not os.path.exists(full_path):
            return full_path
        counter += 1


def is_autogenerated_dir(name, prefix, sub_suffix):
    """
    Returns True if name matches prefix_single_phase_#
    """
    pattern = rf"^{re.escape(prefix)}_{re.escape(sub_suffix)}_\d+$"
    return re.match(pattern, name) is not None


def move_prefixed_items(dir_list, prefix, sub_suffix="single_phase"):
    """
    Moves items starting with prefix, except the auto-generated folders.
    Creates next increment folder like prefix_single_phase_3.
    """

    for base_dir in dir_list:
        if not os.path.isdir(base_dir):
            print(f"Skipping invalid directory: {base_dir}")
            continue

        # Create unique target folder
        new_subdir = generate_unique_dir(base_dir, prefix, sub_suffix)
        os.makedirs(new_subdir, exist_ok=True)

        print(f"Created: {new_subdir}")

        for item in os.listdir(base_dir):
            item_path = os.path.join(base_dir, item)

            # Skip the newly created folder
            if item_path == new_subdir:
                continue

            # Skip auto-generated folders: prefix_single_phase_#
            if is_autogenerated_dir(item, prefix, sub_suffix):
                print(f"Skipping auto-generated folder: {item}")
                continue

            # Move only items starting with prefix
            if item.startswith(prefix):
                target_path = os.path.join(new_subdir, item)
                print(f"Moving: {item_path} → {target_path}")
                shutil.move(item_path, target_path)

        print(f"Done processing {base_dir}\n")


if __name__ == '__main__':
        base_path = "/home/achakroborti1/llam_test/code-generation-by-llm-for-scientific-data"

        climate_list_dirs = [
                f"{base_path}/prompting_techniques/llm_rag_generated_python_scripts",
                f"{base_path}/llm_rag_python_scripts_generation_logs",
                f"{base_path}/user_queries/generated_user_sub_queries",
                f"{base_path}/user_sub_query_generation_logs",
                f"{base_path}/prompting_techniques/zero_shot_sci_data_prompting/tracking_file"
        ]

        matplotagent_list_dirs = [
                f"{base_path}/prompting_techniques/llm_rag_generated_python_scripts",
                f"{base_path}/llm_rag_python_scripts_generation_logs",
                f"{base_path}/user_queries/generated_user_sub_queries",
                f"{base_path}/user_sub_query_generation_logs"
        ]


        fastMRI_list_dirs = [
                f"{base_path}/prompting_techniques/llm_rag_generated_python_scripts",
                f"{base_path}/llm_rag_python_scripts_generation_logs",
                f"{base_path}/user_queries/generated_user_sub_queries",
                f"{base_path}/user_sub_query_generation_logs"
        ]

        
        # model_name = "gpt_oss_20b"
        prefix = "single_phase"

        parser = argparse.ArgumentParser(description="Process model and dataset arguments.")

        # expected arguments
        parser.add_argument("--model", type=str, required=True,
                                help="Model name, e.g. gpt_oss_20b")
        parser.add_argument("--dataset", type=str, required=True,
                                help="Dataset name, e.g. climate")

        args = parser.parse_args()

        # Now you can access args.model and args.dataset
       
        print("Received arguments:")

        list_dirs = []

        if args.dataset and args.dataset=='climate':
                list_dirs = climate_list_dirs
                print(f"  Dataset: {args.dataset}")
       
        elif args.dataset and args.dataset=='matplotagent':
                list_dirs = matplotagent_list_dirs
                print(f"  Dataset: {args.dataset}")
        
       
        elif args.dataset and args.dataset=='fastMRI':
                list_dirs = fastMRI_list_dirs
                print(f"  Dataset: {args.dataset}")
        

        model_name = ""
        if args.model:
            print(f"  Model:   {args.model}")
            model_name = args.model
        

        move_prefixed_items(list_dirs, model_name, prefix)